[package]
name = "aoc2018"
version = "0.1.0"
authors = ["Paul Watson"]
edition = "2018"

[dependencies]
spectral = "0.6.0"
regex = "0.2"
lazy_static = "1.0"
itertools = "0.7.11"
chrono = "0.4.6"
nom = "4"
bmp = "*"
rayon = "1.0"
termion = "*"
#num_bigint = "*"